---

- hosts: all
  sudo: yes
  tasks:
    - name: Packages | Install apt packages
      apt: state=installed update_cache=yes name={{ item }}
      with_items:
        - emacs
        - rhythmbox
        - openssh-server
        - python-dev
        - python-pip
        - python-virtualenv
        - i3
        - virtualbox
        - tmux
        - htop
        - firefox
        - git
        - acpi
        - unrar
        - xclip

    - name: Packages | Upgrade pip
      pip: name=pip state=latest

    - name: Directories | Make workspace
      file: path=~/workspace state=directory

    - name: Configuration | Clone dotfiles
      git: repo=git://github.com/farridav/dotfiles.git dest=~/workspace/dotfiles accept_hostkey=yes

    - name: Configuration | Setup dotfiles
      shell: ~/workspace/dotfiles/setup.sh

    - name: Packages | Download vagrant
      get_url: url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb dest=/tmp/

    - name: Packages | Install vagrant
      apt: deb=/tmp/vagrant_1.7.4_x86_64.deb

    - name: Packages | Download terraform
      get_url: url=https://releases.hashicorp.com/terraform/0.6.6/terraform_0.6.6_linux_amd64.zip dest=/tmp/

    - name: Packages | Install terraform
      unarchive: src=/tmp/terraform_0.6.6_linux_amd64.zip dest=/usr/bin/
